source 'https://rubygems.org'

gem 'rails', '3.2.8'
gem 'sqlite3'
gem 'haml-rails'
gem 'evernote_oauth'
gem 'omniauth-evernote'
gem 'nokogiri'
gem 'coderay'
gem 'rails_autolink'
gem 'execjs'
gem 'therubyracer'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
